name: CI/CD Pipiline

on:
  push:
    branches:
      - master

jobs:

  tests:
    name: Unit and Integration Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: '17'
      - name: Cache Maven Packeges
        uses: actions/cache@v1
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Run List Unit Tests
        run: mvn -f libs/common-starter/pom.xml test
      - name: Run Modules Unit Tests
        run: mvn -f modules/bootstrapper/pom.xml test
      - name: Run Modules Integration Tests
        run: mvn -f modules/bootstrapper/pom.xml verify -Dskip.unit.tests=true